# This is a basic workflow that is manually triggered

name: After Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: Version
        required: true
        type: string
  workflow_run:
    workflows: ["Release"]
    types:
      completed
env:
  NEW_BRANCH: users/readme-bot/update-readme-to-${{ github.event.inputs.version }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    env:
      GH_TOKEN: ${{ github.token }}

    permissions:
      pull-requests: write
      repository-projects: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Validate version
      run: echo ${{ github.event.inputs.version }} | python ./bin/version.py
    - name: Create new branch
      run: git checkout -B ${{ env.NEW_BRANCH }}
    - name: Replace versions in Readme.md
      run: |
        echo ${{ github.event.inputs.version }} | python ./bin/readme_bot.py
        git config user.name "Readme bot"
        git config user.email "readme_bot"
        git commit -a -m "Update versions in README.md to ${{ github.event.inputs.version }}"
        git push -u origin ${{ env.NEW_BRANCH }} --force 
    - name: Create Pull Request
      env:
        GH_PR_COMMAND: gh pr create --base main 
          --head ${{ env.NEW_BRANCH }}
          --title "Update Readme.md for version ${{ github.event.inputs.version }}" 
          --body "This PR is automatic generated." 
          --label "documentation"
      run: |
        echo "### Result of creating PR" >> $GITHUB_STEP_SUMMARY
        if ! ERR=$(bash -c "$GH_PR_COMMAND" 2>&1); then
          echo  "Failed. Reason: \`$ERR\`" >> $GITHUB_STEP_SUMMARY
          echo 'The creation of Pull Request failed. Your project or organization may not allow to create PR in Actions. Run the following command locally:' >> $GITHUB_STEP_SUMMARY
          echo '```'  >> $GITHUB_STEP_SUMMARY
          echo $GH_PR_COMMAND >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        else
          echo 'Succeed' >> $GITHUB_STEP_SUMMARY
        fi
