name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      # We use SemVer, anything before 1.0.0 is a pre-release, but this could also include versions like 1.1.0-beta.
      prerelease:
        description: 'Prerelease'
        required: true
        default: true
        type: boolean
      ado_build_id:
        type: string
        required: true
jobs:
  # Special request from @kyle-rader and @goagain, so no one can create an invalid release.
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Validate version
      run: echo ${{ github.event.inputs.version }} | python ./bin/version.py

  # Build and sign Linux binaries on Azure DevOps and publish them to GitHub and packages.microsoft.com.
  linux_release:
    runs-on: ubuntu-latest
    needs: [validate]
    env:
      ADO_LINUX_ARTIFACT_DOWNLOAD_PATH: dist/linux
      ADO_LINUX_ARTIFACT_NAME: ${{ vars.ADO_LINUX_ARTIFACT_NAME }}
      DEBIAN_REVISION: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build, Sign and Download Linux Binaries
      run: |
        pip install -r bin/requirements.txt
        python ./bin/trigger_azure_pipelines.py
      env:
        AZURE_DEVOPS_BUILD_PAT: ${{ secrets.AZURE_DEVOPS_BUILD_PAT }}
        ADO_ORGANIZATION: ${{ secrets.ADO_ORGANIZATION }}
        ADO_PROJECT: ${{ secrets.ADO_PROJECT}}
        ADO_BUILD_ID: ${{ github.event.inputs.ado_build_id }}
    - name: Upload linux-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-linux-x64.deb
        path: ${{ env.ADO_LINUX_ARTIFACT_DOWNLOAD_PATH }}/${{ env.ADO_LINUX_ARTIFACT_NAME }}/azureauth_${{ github.event.inputs.version }}-${{ env.DEBIAN_REVISION }}_amd64.deb
    - name: Upload linux-arm64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: azureauth-${{ github.event.inputs.version }}-linux-arm64.deb
        path: ${{ env.ADO_LINUX_ARTIFACT_DOWNLOAD_PATH }}/${{ env.ADO_LINUX_ARTIFACT_NAME }}/azureauth_${{ github.event.inputs.version }}-${{ env.DEBIAN_REVISION }}_arm64.deb

  release:
    runs-on: ubuntu-latest
    needs: [linux_release]
    # The 'release' environment is what requires reviews before creating the release.
    environment:
      name: release
    # These permissions are required in order to use `softprops/action-gh-release` to upload.
    permissions:
      contents: write
    steps:
    - name: Download linux-x64 artifact
      uses: actions/download-artifact@v3
      with:
        path: azureauth-${{ github.event.inputs.version }}-linux-x64.deb
        name: azureauth-${{ github.event.inputs.version }}-linux-x64.deb
    - name: Download linux-arm64 artifact
      uses: actions/download-artifact@v3
      with:
        path: azureauth-${{ github.event.inputs.version }}-linux-arm64.deb
        name: azureauth-${{ github.event.inputs.version }}-linux-arm64.deb

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.version }}
        body: "Release ${{ github.event.inputs.version }}. See [`CHANGELOG.md`](https://github.com/AzureAD/microsoft-authentication-cli/blob/${{ github.event.inputs.version }}/CHANGELOG.md) for updates."
        tag_name: ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: |
          azureauth-${{ github.event.inputs.version }}-linux-x64.deb
          azureauth-${{ github.event.inputs.version }}-linux-arm64.deb
  
